#!/bin/bash -
PATH=/bin:/usr/bin:/sbin:/usr/sbin

if [[ -z "$1" ]]
then
  echo "Usage: $0 from.com https://www.to.com/"
  exit
fi

if [[ -z "$SUDO_USER" ]]
  then
  echo "Use sudo"
  exit
fi

CHOICES="Overwrite Skip"

# The domain being created
DOMAIN=$1
TARGET_URL=$2

# This directory holds the templates for the apache and logrotate conf files
DEFAULT_TEMPLATE_DIR="$(dirname $0)/templates"
USER_TEMPLATE_DIR="/home/$SUDO_USER/a2mksite_templates"

# This is where we'll create the conf files
APACHE_CONF_DIR="/etc/apache2/sites-available"

# These are the conf files
APACHE_CONF="$APACHE_CONF_DIR/$DOMAIN.conf"

# FUNCTIONS ==========================================================

function mk_apache_conf {
  echo "Creating apache config file: $APACHE_CONF..."
  sed -e "s^THE_DOMAIN^$DOMAIN^g"\
      -e "s^TARGET_URL^$TARGET_URL^g"\
      "$APACHE_TEMPLATE" > "$APACHE_CONF"
  echo "done!"

  echo "Chowning apache config file to root..."
  chown 0:$SUDO_GID "$APACHE_CONF"
  echo "done!"

  echo "Chmoding apache config file to 740..."
  chmod 740 "$APACHE_CONF"
  echo "done!"
}

# Determine template directories ========================

# Choose the user's apache-redirect.conf template first
# If it doesn't exist, use the default
if [[ -f "$USER_TEMPLATE_DIR/apache-redirect.conf" ]]
  then APACHE_TEMPLATE="$USER_TEMPLATE_DIR/apache-redirect.conf"
elif [[ -f "$DEFAULT_TEMPLATE_DIR/apache-redirect.conf" ]]
  then APACHE_TEMPLATE="$DEFAULT_TEMPLATE_DIR/apache-redirect.conf"
else
  echo "No apache-redirect.conf template can be found. Aborted."
  exit
fi

# Create necessary directories ==========================

if [[ ! -d "$APACHE_CONF_DIR" ]]
  then
  mkdir -p "$APACHE_CONF_DIR"
  chgrp $SUDO_GID "$APACHE_CONF_DIR"
fi

# Run those functions ====================================

if [[ -f "$APACHE_CONF" ]]
  then
  echo "$APACHE_CONF already exists..."
  select choice in $CHOICES; do
    if [ $choice ]; then
      case $choice in
        Overwrite)
          mk_apache_conf
          break;;
        Skip) break;;
        esac
    else
      echo 'Invalid selection'
    fi
  done
  else
  mk_apache_conf
fi

# FINISH UP ==================================
echo "Enabling Site..."
/usr/sbin/a2ensite $DOMAIN
echo "Restarting Apache..."
/usr/sbin/apache2ctl graceful
echo "ALL DONE!"
