#!/bin/bash -
PATH=/bin:/usr/bin:/sbin:/usr/sbin

if [[ -z "$1" ]]
then
  echo "Usage: $0 domain.com"
  exit
fi

if [[ -z "$SUDO_USER" ]]
  then
  echo "Use sudo"
  exit
fi

# The domain being created
DOMAIN=$1

# This is where we'll create the conf files
APACHE_CONF_DIR="/etc/apache2/sites-available"
LOGROTATE_CONF_DIR="/etc/logrotate.d"

# These are the conf files
APACHE_CONF="$APACHE_CONF_DIR/$DOMAIN.conf"

# FUNCTIONS ==========================================================

function rm_apache_conf {
  echo "Removing apache config file: $APACHE_CONF..."
  rm "$APACHE_CONF"
  echo "done!"
}

# Disable stuff ==========================================

echo "Disablinig Site..."
/usr/sbin/a2dissite $DOMAIN
echo "Restarting Apache..."
/usr/sbin/apache2ctl graceful

# Run those functions ====================================

if [[ -f "$APACHE_CONF" ]]
  then
  read -p "Remove $APACHE_CONF? " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]
    then
    rm_apache_conf
  fi
fi

# FINISH UP ==================================
echo "ALL DONE!"
